### PR TITLE
Ti 6 ready, stetho update, clean up project

### PR DESCRIPTION
**Pull request by m1ga**
Changelog:
* Ti 6 ready
* removed unnecessary folders
* Updated stetho

*no new features!*

### CODE REVIEW

**Comment by 7daysofrain** [comment]
Nice!,

Im no longer working with Titanium so this was a litter abbandoned. Thanks

**Comment by m1ga** [comment]
Thanks for merging even though you aren't using Ti anymore :) 
I'll found this while searching for stetho not sure if it can be useful but at least it works now with the newest SDK and I can dig depper!

**Comment by m1ga** [comment]
Oh, and I moved the binary to the release tab, so could you please upload https://github.com/m1ga/ti-stetho/releases/tag/2.0 so people can test it

**Comment by 7daysofrain** [comment]
hi, updated the readme pointing to your release ;)

2017-03-27 21:29 GMT+02:00 Michael <notifications@github.com>:

**Pull request merged**
